name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  faker: ^2.0.0
  google_fonts: ^5.1.0
  get: ^4.6.5
  dio: ^5.3.3
  path_provider: ^2.1.1
  flutter:
    sdk: flutter
  ex_kit:
    path: ../

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli: 
  sub_folder: false

