name: example
publish_to: none
version: 1.0.0
description: Demonstrates how to use the kotlin_scope_function plugin.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  faker: ^2.0.0
  google_fonts: ^4.0.4
  flutter_html: ^2.2.1
  dart_code_viewer2: ^1.0.1
  get: ^4.6.5
  get_storage: ^2.1.1

dependency_overrides:
  flutter_svg: ^1.0.0

  flutter:
    sdk: flutter
  ex:
    path: ../

flutter:
  uses-material-design: true

get_cli:
  sub_folder: false

