include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    unnecessary_import: ignore
    unnecessary_null_comparison: ignore
  exclude:
    - "bin/cache/**"
    - "dev/conductor/lib/proto/*"
    - "lib/generated/**"
    - "script/**"
    - "lib/src/ex_api/**"


linter:
  rules: