name: ex
description: Powerfull Ex-Material UI (Material UI improvement)
version: 0.1.8
homepage: https://github.com/abehbatre/ex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  http: ^0.13.5
  intl: ^0.17.0
  velocity_x: ^3.6.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  photo_view: ^0.14.0

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/