name: ex
description: Powerfull & Fully Customize Material UI |  all material widget with functional many helper/utils like `ExHttp, ExLog, ExAlert, ExBottomSheet, ExDialog, ExSnackbar` 
version: 0.3.0
homepage: https://github.com/abehbatre/ex

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  get: ^4.6.5
  photo_view: ^0.14.0
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/