name: ex
description: Fully Customize Material UI |  all material widget with functional many helper/utils like `ExHttp, ExLog, ExAlert, ExBottomSheet, ExDialog, ExSnackbar` 
version: 0.4.4
homepage: https://github.com/aditgpt/ex
repository: https://github.com/aditgpt/ex
issue_tracker: https://github.com/aditgpt/ex/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  get: ^4.6.6
  photo_view: ^0.14.0
  velocity_x: ^4.1.1
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/