name: ex
description: Scope Function, When Expression, ExComponent, ExLog, ExAlert, ExBottomSheet, ExLoading, ExImagePreview, ExUtils
version: 0.0.2
homepage: https://github.com/abehbatre/ex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  velocity_x: ^3.4.0
  flutter_svg: ^1.0.3
  photo_view: ^0.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
