name: ex
description: Scope Function, When Expression, ExComponent, ExLog, ExAlert, ExBottomSheet, ExLoading, ExImagePreview, ExUtils
version: 0.0.1
homepage: https://github.com/abehbatre/ex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  logger: ^1.1.0
  velocity_x: ^3.0.0
  flutter_svg: ^0.22.0
  lottie: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  loading_animation_widget: ^1.1.0+1
  photo_view: ^0.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
