// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yJ76_A__nCeVSERwAUKnW-Do6qStyBg',
    appId: '1:200688103785:web:fa86b78939c5c79551cdf8',
    messagingSenderId: '200688103785',
    projectId: 'ex-kit',
    authDomain: 'ex-kit.firebaseapp.com',
    storageBucket: 'ex-kit.appspot.com',
    measurementId: 'G-TKX3DHQEHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiWOb_3aHBJqY3_qCGajHB94VXZgYyFE',
    appId: '1:200688103785:android:29d2b83315168f2351cdf8',
    messagingSenderId: '200688103785',
    projectId: 'ex-kit',
    storageBucket: 'ex-kit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDY6P39DJowMr2WfameuzV1fMRt28iFE',
    appId: '1:200688103785:ios:ddd5fd573e0be13651cdf8',
    messagingSenderId: '200688103785',
    projectId: 'ex-kit',
    storageBucket: 'ex-kit.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbDY6P39DJowMr2WfameuzV1fMRt28iFE',
    appId: '1:200688103785:ios:6a9e23732bd79b5051cdf8',
    messagingSenderId: '200688103785',
    projectId: 'ex-kit',
    storageBucket: 'ex-kit.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
